### PR TITLE
Ali bugs fix

### PR DESCRIPTION
**Pull request by Daebaks**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
- [x] Test B

**Test Configuration(if any)**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Daebaks** [comment]
in some bugs I left the commented-out code because it has future use.

**Review by Ebube111 — COMMENTED** [review]
Work on failing test, then dm me for re-review

**Comment by codingshot** [comment]
there is casing issues with core principles, need for padding and slider
typing with custom amount

**Comment by ltran0817** [comment]
All the changes in this request are fixing syntax and minor styles changes. Didn't introduce new bug/warning compare to before the pr

**Comment by Daebaks** [comment]
I committed more bugs, and fixed casing and padding as well as fixed typos and other bugs but I haven't made a pr yet, they are committed though. Also, locally I will do more work.

**Pull request merged**
